import type { Metadata } from 'next'

import { Inter } from 'next/font/google'

import './globals.css'
import { Header } from '@/components/Header/header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja" suppressHydrationWarning>
      <body className={inter.className}>
        <Header />
        <div className="mx-auto mt-4 grid w-full max-w-7xl grid-flow-row grid-rows-[auto_1fr] px-4">
          {children}
        </div>
      </body>
    </html>
  )
}
